version: "3"
services:
  node:
    build: .
    ports:
      - "7878:7878"
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - backend
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: .env
    networks:
      - backend
networks:
  backend:
